# Generated by Django 5.2.16 on 2026-08-02 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('frame_ref', models.CharField(max_length=32)),
                ('defect_class', models.CharField(max_length=64)),
                ('confidence', models.FloatField()),
                ('bounding_box', models.JSONField(blank=True, null=True)),
                ('model_id', models.CharField(blank=True, default='', max_length=128)),
                ('detected_at', models.DateTimeField()),
                ('reviewed', models.BooleanField(default=False)),
                ('queue_status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('relabeled', 'Relabeled')], default='pending', max_length=32)),
                ('queue_path', models.CharField(blank=True, default='', max_length=512)),
                ('queue_reason', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(default=dict)),
                ('gold_path', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_findings', to='fleet.asset')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('relabel', 'Relabel')], max_length=16)),
                ('relabel_class', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='review.inspectionfinding')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
